name: tmda
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  solar_icons: ^0.0.5
  injectable: ^2.6.0
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  auto_route: ^10.2.2
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  get_it: ^9.0.5
  json_annotation: ^4.9.0
  shimmer: ^3.0.0
  lottie: ^3.3.2
  build_runner: ^2.10.4
  flutter_svg: ^2.2.2
  auto_size_text: ^3.0.0
  injectable_generator: ^2.7.0
  auto_route_generator: ^10.1.0
  cached_network_image: ^3.4.1
  responsive_framework: ^1.5.1
  bouncing_widget: ^2.0.0
  intl: ^0.20.2
  permission_handler: ^12.0.1
  internet_connection_checker_plus: ^2.9.1+2
  url_launcher: ^6.3.2
  flutter_cache_manager: ^3.4.1
  flash: ^3.1.1
  http: ^1.6.0
  dio: ^5.9.0
  location: ^8.0.1
  collection: ^1.18.0
  youtube_player_flutter: ^9.0.3
  flutter_native_splash: ^2.4.7
  carousel_slider: ^5.1.1
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  json_serializable: ^6.11.1


flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/jsons/
    - assets/svgs/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 100

